- .github/workflows/rust.yaml
- core/engine/src/engine.rs
- core/engine/src/handler/tree.rs
Adds rust workflow, which includes:
- Benchmarks
- Tests
- Miri (for memory leaks)
> feat: add rust workflow;

- core/vm/src/opcodes.rs
Removes unused clone method and cleans up implementation of some existing ones.
> chore: cleanup opcodes methods;

- core/expression/src/opcodes.rs
- core/expression/src/vm.rs
- core/expression/tests/isolate.rs
- fixes nested scopes
- implements From<&serde_json::Value> trait for ExecResult for ease of use
> fix: nested expression scopes;

- core/engine/src/handler/table/zen.rs
- core/expression/src/isolate.rs
Adds reference map to evaluation traces for easier debugging
> feat: evaluation reference map trace;

- core/expression/src/parser/unary/mod.rs
Fixes edge cases for unterminated statements in unary parser.
> fix: unterminated statement

- core/engine/src/handler/table/mod.rs
- core/engine/src/handler/table/zen.rs
Fixes collision issues of JSON outputs when multiple names collide and implements a predictable behaviour for such cases
> fix: decision table json ordering;

- bindings/nodejs/package.json
- bindings/nodejs/src/engine.rs
- bindings/nodejs/src/loader.rs
Fixes NAPI open handle which caused improper test teardown and hanging process.
> fix: napi open handle

- core/engine/Cargo.toml
- core/expression/src/parser/iter.rs
- core/expression/src/parser/standard/mod.rs
- core/expression/src/parser/unary/mod.rs
- core/expression/tests/isolate.rs
Fix bug report under #48.
Will do some performance benchmarks, and potentially change the approach, while adding a couple of extra tests.
> fix: expression date range;

- core/expression/src/parser/standard/mod.rs
- core/expression/tests/isolate.rs
Extends the allowed parameters for 2nd argument in dual arity function(s).
> fix: dual arity argument parsing;

- core/engine/src/handler/table/zen.rs
Adds `_description` to traceData
> fix: improve trace data;

- bindings/nodejs/src/decision.rs
- bindings/nodejs/src/engine.rs
- bindings/python/src/decision.rs
- bindings/python/src/engine.rs
- core/engine/src/error.rs
Adds more details about failure (nodeId, cause, etc.).
> fix: implement serializable errors; improve binding error transparency;

- core/expression/src/compiler.rs
- core/expression/src/opcodes.rs
- core/expression/src/parser/standard/constants.rs
- core/expression/src/parser/standard/mod.rs
- core/expression/src/parser/unary/constants.rs
- core/expression/src/vm.rs
- core/expression/tests/isolate.rs
- core/expression/tests/standard.rs
- core/expression/tests/unary.rs
Adds `year` operator, cleans handlers for null values and handles hanging standard parser in a better way.
> feat: standardise operators;

- Cargo.toml
- bindings/nodejs/Cargo.toml
- bindings/nodejs/index.d.ts
- bindings/nodejs/index.js
- bindings/nodejs/src/expression.rs
- bindings/nodejs/src/lib.rs
- bindings/nodejs/test/decision.spec.ts
- bindings/python/Cargo.toml
- bindings/python/index.py
- bindings/python/src/expression.rs
- bindings/python/src/lib.rs
- core/engine/Cargo.toml
- core/expression/Cargo.toml
- core/expression/src/isolate.rs
Exposes expressions through Node.js and Python bindings.
> feat: expose expressions through bindings;

- core/expression/src/compiler.rs
- core/expression/src/opcodes.rs
- core/expression/src/vm.rs
- core/expression/tests/data/standard.csv
Fixes an issue when attempting to access string at an index.
Removes unnecessary type from VM (Int) in favour of "Number".
> fix: string slices; remove int variable type;

- core/expression/src/compiler.rs
- core/expression/src/opcodes.rs
- core/expression/src/parser/standard/constants.rs
- core/expression/src/parser/unary/constants.rs
- core/expression/src/vm.rs
- core/expression/tests/data/standard.csv
Adds type conversion functions for:
- string - can be converted from number, string (passthrough) and bool
- number - can be converted from number (passthrough), string and bool
> feat: type conversions;

- core/expression/src/compiler.rs
- core/expression/src/opcodes.rs
- core/expression/src/parser/standard/constants.rs
- core/expression/src/parser/unary/constants.rs
- core/expression/src/vm.rs
- core/expression/tests/data/standard.csv
Adds a new function for checking if argument is numeric.
> feat: is numeric function;

- actions/cargo-version-action/dist/index.js
- actions/cargo-version-action/src/cargo.ts
- actions/cargo-version-action/src/index.spec.ts
- bindings/c/Cargo.toml
- bindings/c/src/expression.rs
- bindings/nodejs/Cargo.toml
- bindings/nodejs/src/expression.rs
- bindings/nodejs/src/types.rs
- bindings/python/Cargo.toml
- bindings/python/src/expression.rs
- bindings/python/src/types.rs
- core/engine/Cargo.toml
- core/engine/src/handler/custom_node_adapter.rs
- core/template/Cargo.toml
- core/template/tests/template.rs
Crate `zen-template` needs to be renamed as it's already taken.
> fix: rename templates crate

- bindings/nodejs/index.d.ts
- bindings/nodejs/index.js
- bindings/nodejs/src/content.rs
- bindings/nodejs/src/engine.rs
- bindings/nodejs/src/lib.rs
- bindings/nodejs/src/loader.rs
- bindings/nodejs/test/decision.spec.ts
Add new class `ZenDecisionContent` in Node.js and improve binding ergonomics.
> feat: improve nodejs bindings

- bindings/nodejs/index.d.ts
- bindings/nodejs/index.js
- bindings/nodejs/package.json
- bindings/nodejs/src/decision.rs
- bindings/nodejs/src/engine.rs
- bindings/nodejs/src/lib.rs
- bindings/nodejs/src/safe_result.rs
- bindings/nodejs/yarn.lock
Add an alternative interface for NodeJS (e.g. safeEvaluate).
> feat: safe nodejs api

- core/engine/src/handler/graph.rs
- test-data/switch-performance-2.json
Improves graph performance by reducing cloning, fixes issue with recursive clones of `$nodes`.
> fix: graph performance

- core/expression/Cargo.toml
- core/expression/src/compiler/compiler.rs
- core/expression/src/compiler/opcode.rs
- core/expression/src/parser/builtin.rs
- core/expression/src/parser/unary.rs
- core/expression/src/vm/vm.rs
- core/expression/tests/data/standard.csv
Adds experimental fuzzy match function. It should not be used, as it might change in near future.
> feat: fuzzy match

- core/engine/src/error.rs
- core/engine/src/handler/expression/mod.rs
- core/engine/src/handler/function/function.rs
- core/engine/src/handler/function/mod.rs
- core/engine/src/handler/function/module/console.rs
- core/engine/src/handler/graph.rs
- core/engine/src/handler/node.rs
- core/engine/src/handler/table/zen.rs
This PR improves the decision engine's tracing and error handling capabilities by adding partial trace support and enhancing error reporting with detailed context. These changes make it easier to debug and understand decision execution failures.
The change significantly improves debugging capabilities by providing better context when errors occur during decision execution.
✨ Added partial trace support to capture execution context even when errors occur
🔍 Enhanced error reporting with detailed trace information for debugging
📝 Improved function handler logging to capture errors in execution trace
🛠️ Refined trace data serialization with graceful fallback handling
> feat: partial trace

- bindings/python/Cargo.toml
- bindings/python/src/custom_node.rs
- bindings/python/src/decision.rs
- bindings/python/src/engine.rs
- bindings/python/src/lib.rs
- bindings/python/src/mt.rs
- bindings/python/test_async.py
- bindings/python/test_sync.py
- test-data/http-function.json
- test-data/sleep-function.json
This PR enhances the Python bindings with proper async runtime handling and adds test coverage for async operations like HTTP requests and sleep functions.
- ✨ Added proper Tokio runtime initialization for async operations
- 🧪 Added test coverage for async HTTP calls and sleep functions
- 🔄 Improved synchronous operation handling with dedicated runtime
- Updated Python bindings to use explicit Tokio runtime initialization
> fix: python async

- core/expression/src/vm/vm.rs
🐛 Added fallback mechanism when decimal exponentiation fails
⚡ Now gracefully switches to floating-point calculation instead of crashing
> fix: lossy exponent fallback
