gorules/zen

bindings/nodejs/src/decision.rs, bindings/nodejs/src/engine.rs, bindings/nodejs/src/loader.rs, bindings/python/src/loader.rs, core/engine/src/decision.rs, core/engine/src/engine.rs, core/engine/src/error.rs, core/engine/src/handler/tree.rs, core/engine/src/lib.rs, core/engine/src/loader/filesystem.rs, core/engine/src/loader/memory.rs, core/engine/src/loader/mod.rs, core/engine/src/loader/noop.rs, test-data/infinite-function.json
Adds more transparency to errors being thrown on the top level. Boxing top-level errors is done to stabilise the API if the error types grow larger than the Ok Result variant and reduce the need for API changes in the future.
=> fix: error propagation;

core/engine/src/handler/table/zen.rs, core/expression/src/isolate.rs, core/expression/src/opcodes.rs, core/expression/tests/isolate.rs
Removes `ExecResult` as it is an unnecessary indirection. Start using serde Value directly instead.
=> refactor: remove exec result;

core/engine/src/handler/table/zen.rs, core/expression/src/isolate.rs, core/expression/tests/isolate.rs
Fixes a case where the standard parser would kick in if the string contained "$", instead we will be checking for the exact identifier with the exact value after tokenization.
=> fix: unary reference in string;

core/engine/src/handler/expression/mod.rs
Temporary solution for displaying an error for expression node. There will be a bigger rewrite to how errors are handled in the future.
=> improvement: expression error visibility;

bindings/nodejs/index.d.ts, bindings/nodejs/src/decision.rs, bindings/nodejs/src/engine.rs, bindings/nodejs/src/loader.rs
Fixes an issue with export names from TypeScript likely caused by `js_name` aliasing.
=> fix: ts evaluate options;

core/expression/src/compiler.rs, core/expression/src/opcodes.rs, core/expression/src/parser/standard/constants.rs, core/expression/src/parser/unary/constants.rs, core/expression/src/vm.rs, core/expression/tests/isolate.rs
Adds support for:
`median(arr)` and `mode(arr)`.
Also fixes a small issue with trailing zeros in number normalisation during  `zen_expression::Variable` -> `serde::Value`.
=> feat: additional math functions;

core/engine/src/handler/table/zen.rs, core/engine/src/model/mod.rs, core/expression/src/isolate.rs, core/expression/src/lexer/codes.rs, core/expression/src/lexer/lexer.rs
Adds an optional field for the Decision model, and changes the trace slightly (to avoid collisions).
The rationale is that we want to be able to write pure expressions in decision inputs without setting any selector.
=> feat: optional field for decision model;

core/expression/src/compiler.rs, core/expression/src/parser/standard/constants.rs, core/expression/src/parser/unary/constants.rs, core/expression/tests/isolate.rs
Removes unimplemented function from zen expression language.
Affected:
`seasonOfYear` - not useful, and cannot be properly extracted from chrono
`weekOfMonth` - same as above
Added a test for 1 missing function case.
=> fix: remove missing date fns;

README.md, bindings/nodejs/README.md, bindings/python/README.md
Was going through the README and found a typo which triggered a few aesthetic changes.
- Rename `darvin` to `darwin`
- New line, before and after header in README
- Remove trailing spaces
- Prettify raw markdown table so that it is easier to read
=> Minor aesthetic changes in README

bindings/nodejs/index.d.ts
regenerates type for `validate` function in typescript
=> fix: node type

bindings/c/src/custom_node.rs, bindings/c/src/engine.rs, bindings/c/src/loader.rs, bindings/c/zen_engine.h
This leak affects only custom node (in Go) which is currently under development and not part of Go release.
=> fix: go memory leak

bindings/nodejs/Cargo.toml, bindings/nodejs/README.md, bindings/nodejs/index.d.ts, bindings/nodejs/src/custom_node.rs, bindings/nodejs/src/engine.rs, bindings/nodejs/src/loader.rs, bindings/nodejs/test/decision.spec.ts
Adds a new function `dispose` to ZenEngine. This function should be called to ensure proper clean up of memory when creating large numbers of `ZenEngine` instances.
In future, this will be made automatic when NAPI-RS releases new version.
=> feat: add nodejs dispose function

core/expression/tests/isolate.rs, core/expression/tests/standard.rs
Just checking that f64, i64, and u64 types serialize back and forth into the isolate environment
=> Add a few tests around numerics

bindings/python/Cargo.toml, bindings/python/index.py, bindings/python/pyproject.toml, bindings/python/src/custom_node.rs, bindings/python/src/decision.rs, bindings/python/src/engine.rs
I think there is a discrepancy with the NodeJS binding it can evaluate the customer_handler async but the python binding appears not to be able to do this.
I think some async support for the custom node handler in python would be a good add, so for example if you are making an API request in a custom node handler, not blocking the event loop during execution.
However async could be added by the zen team would be appreciated, this PR just to make the ask.
=> feat: add async support to python binding

core/engine/src/handler/traversal.rs, core/expression/src/variable/mod.rs
Fixes a case where, during the merge, Rc pointers are equal leading to a double borrow. Also handles an existing unwrap using filter_map for better stability.
=> fix: double borrow

core/engine/src/handler/decision.rs, core/engine/src/model/mod.rs
This PR adds a new functionality to decision nodes, allowing you to map the inputs being sent to the node, choosing the execution mode and the output path.
For now this property will be present only on `DecisionNode`, but this will likely be extended to `DecisionTableNode` and `ExpressionNode`.
=> feat: decision transform attributes

core/expression/src/intellisense/types/provider.rs, core/expression/src/parser/parser.rs, core/expression/src/variable/types/mod.rs
Adds few hints to existing intellisense type errors. Also implements `Hash` trait for `VariableType` as it's needed for some operations in WASM context.
=> fix: improve type errors

Cargo.toml, core/engine/Cargo.toml, core/engine/benches/engine.rs, core/engine/src/handler/function/module/console.rs, core/engine/src/handler/table/zen.rs, core/expression/src/isolate.rs, test-data/graphs/table-loop.json
This PR addresses two separate issues:
🐛 Fixed caching issue where isolate environment wasn't properly cleared between loop iterations
🧹 Added clear_references() method to Isolate struct
✅ Added test case verifying loop cache behaviour
The fix ensures proper evaluation of loop-based tables, preventing cached values from affecting subsequent iterations.
⬆️ Updated rquickjs to version 0.8.0
🗑️ Removed custom rquickjs-core patch
These changes were required to address Windows CI pipeline issues and keep our QuickJS implementation up-to-date.
=> feat: bump rquickjs, fix loop cache for decisionTable

.github/workflows/node.yaml, README.md, bindings/nodejs/README.md, bindings/nodejs/npm/linux-arm64-musl/README.md, bindings/nodejs/npm/linux-arm64-musl/package.json, bindings/nodejs/npm/linux-x64-musl/README.md, bindings/nodejs/npm/linux-x64-musl/package.json, bindings/nodejs/package.json
See https://github.com/gorules/zen/issues/44 and https://github.com/gorules/zen/issues/218.
This pull request:
- extends the Node.js build matrix to build targets `aarch64-unknown-linux-musl` and `x86_64-unknown-linux-musl`
- extends the testing coverage to test the new artifacts `bindings-x86_64-unknown-linux-musl` and `bindings-aarch64-unknown-linux-musl`
- adds the scaffold files to `bindings/nodejs/npm` for the new build targets
- updates the readme to reflect the new platform compatibility
The workflows have been tested on my repository fork https://github.com/kyle-mwnz/zen/actions/runs/12018556311
Thank you!
**If there is anything I can do to expedite this pull request, please let me know and I can hopefully address this promptly.**
=> feat: musl builds for Node.js

core/engine/src/handler/traversal.rs, test-data/graphs/nested-request.json
Node Data Merge Strategy Update
This PR updates the node data merging mechanism in the graph traversal system to ensure proper handling of nested data structures and prevent unwanted mutations.
🔄 Changed node data merging from merge to merge_clone to preserve data integrity
✅ Added test case for nested request handling with complex data structures
The core change switches from using merge to merge_clone when combining node data during graph traversal. This ensures that source data remains unmodified while properly handling nested objects.
=> fix: node merge strategy

core/engine/src/handler/graph.rs, core/engine/src/handler/traversal.rs
This PR gives us insight into how nodes are executed by adding a simple order counter to each trace. This makes debugging so much easier since we can now see exactly what ran and when.
✨ Track order of execution for each node
🎨 Cleaned up the tracing code to be less repetitive
⚡ Performance timings now show one decimal place (looks nicer!)
=> feat: add order to trace

core/expression/src/parser/parser.rs, core/expression/src/parser/standard.rs, core/expression/src/parser/unary.rs, core/expression/tests/data/unary.csv
This PR fixes a bug where multiple conditions using logical operators (`and`, `or`) were not working correctly within closure expressions when using the Unary parser mode. The fix specifically addresses cases like `some($, # > 10 and # < 20)` where the Unary parser was prematurely breaking on logical operators.
- 🐛 Fixed handling of logical operators (`and`, `or`) in Unary parser's closure expressions
- ✨ Added context awareness to prevent premature breaks on logical operators in closure contexts
- 🔧 Modified Unary parser's binary expression evaluation to respect closure context
Previously failing expressions that now work in Unary mode:
```js
some($, # > 10 and # < 20)    // Previously broke on 'and'
```
- Added `ParserContext` to differentiate between global and closure contexts in …
=> fix: unary closure expression

bindings/python/src/expression.rs, bindings/python/zen.pyi
This PR removes the `evaluate_many` functionality from Python bindings after performance analysis showed minimal benefits compared to sequential evaluation.
- 🔥 Removed `evaluate_many` method from `Expression` class
- 🧹 Cleaned up associated types and error handling code
- 📝 Updated Python type definitions to reflect the changes
Not needed, as the Python version with compiled expressions hasn't been released yet.
=> feat: pyexpr remove evaluate many

bindings/python/Cargo.toml, bindings/python/src/expression.rs, bindings/python/src/lib.rs, bindings/python/zen.pyi, core/expression/src/validate.rs
This PR refactors the expression validation system in Python bindings to reduce code complexity while maintaining full validation capabilities.
=> fix: py validate methods

core/expression/src/parser/parser.rs
This PR improves error handling and reporting when a closing parenthesis is missing in a function call. Previously, these errors were not correctly reported.
=> fix: open bracket error

core/expression/src/vm/error.rs, core/expression/src/vm/variable.rs, core/expression/src/vm/vm.rs, core/expression/tests/data/standard.csv
This PR adds support for interval notation as iterable objects in expressions, allowing iteration over numeric ranges with inclusive or exclusive boundaries.
- Updated the VM's `Begin` opcode handler to support interval objects
- Improved error messages in the VM for better debugging
- Added comprehensive tests for all interval notation combinations:
- `[0..3]` (inclusive-inclusive)
- `(0..3]` (exclusive-inclusive)
- `[0..3)` (inclusive-exclusive)
- `(0..3)` (exclusive-exclusive)
```
map([0..3], #)    // Returns [0, 1, 2, 3]
map((0..3], #)    // Returns [1, 2, 3]
map([0..3), #)    // Returns [0, 1, 2]
map((0..3), #)    // Returns [1, 2]
```
This enhancement provides a more concise and expressive way to iterate over numeric ranges in expressions, similar to range syntax found in many …
=> feat: interval iterator

core/expression/src/functions/internal.rs, core/expression/src/lexer/lexer.rs, core/expression/src/parser/parser.rs, core/expression/src/variable/conv.rs, core/expression/src/variable/de.rs, core/expression/tests/data/standard.csv
Thanks @Machine-Maker (had to make few modifications in lexer as well)
=> feat: number scientific notation
